name: C/C++ CI

on:
  push:
    branches: [ auto_build ]
  pull_request:
    branches: [ auto_build ]

env:
  BUILD_DIR: ModuleRadio/Firmware/src/ZiGate/Build/ZigbeeNodeControlBridge/
  SDK_DIR: ModuleRadio/Firmware/src/sdk

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get toolchain
      run: mkdir -p ${{ env.SDK_DIR }}/Tools && wget https://github.com/openlumi/BA2-toolchain/releases/download/20201219/ba-toolchain-20201219.tar.bz2 -O - | tar -jx -C ${{ env.SDK_DIR }}/Tools && ln -s ba-toolchain ${{ env.SDK_DIR }}/Tools/ba-elf-ba2-r36379
    - name: Install xmltodict
      run: pip3 install xmltodict
    - name: make
      id: make
      run: |
        for NODE in COORDINATOR FULL_FUNC_DEVICE; do for BAUD in 115200 1000000; do for CHIP in JN5169 JN5168; do for GP in 0 1; do
          make -j8 -C $BUILD_DIR NODE=$NODE GP_SUPPORT=$GP BAUD=$BAUD JENNIC_CHIP=$CHIP JENNIC_CHIP_FAMILY=JN516x
          make -C $BUILD_DIR BAUD=0 clean
        done done done done
        echo "::set-output name=status::success"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      if: steps.make.outputs.status == 'success' && !cancelled()
      with:
        # Artifact name
        name: zigate_firmwares.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.BUILD_DIR }}/*.bin
